server:
  port: 8080

spring:
  application:
    name: gateway
  config:
    import: "optional:configserver:http://localhost:8888"
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: customer-service
          uri: lb://customer-service
          predicates:
            - Path=/api/v1/customers/**
        - id: flight-service
          uri: lb://flight-service
          predicates:
            - Path=/api/v1/flights/**, /api/v1/routes/**, /api/v1/aircraft/**
        - id: booking-service
          uri: lb://booking-service
          predicates:
            - Path=/api/v1/bookings/**
        - id: check-in-service
          uri: lb://check-in-service
          predicates:
            - Path=/api/v1/check-ins/**
        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/api/v1/notifications/**
        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/api/v1/payments/**
        - id: revenue-service
          uri: lb://revenue-service
          predicates:
            - Path=/api/v1/revenue/**
        - id: reporting-service
          uri: lb://reporting-service
          predicates:
            - Path=/api/v1/reports/**
        - id: accounting-service
          uri: lb://accounting-service
          predicates:
            - Path=/api/v1/accounting/**
        - id: search-service
          uri: lb://search-service
          predicates:
            - Path=/api/v1/search/**
        - id: inventory-service
          uri: lb://inventory-service
          predicates:
            - Path=/api/v1/inventory/**, /api/v1/seats/**
        - id: reservation-service
          uri: lb://reservation-service
          predicates:
            - Path=/api/v1/reservations/**
        - id: customer-profile-service
          uri: lb://customer-profile-service
          predicates:
            - Path=/api/v1/profile/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always 